# Generated by Django 3.2.9 on 2021-12-03 11:18
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapingstate',
            name='use_proxy',
            field=models.BooleanField(default=False),
        ),
    ]
