# Generated by Django 3.2.9 on 2021-12-12 09:29
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_scrapingstate_use_proxy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapingstate',
            name='spider_name',
        ),
    ]
