# Generated by Django 3.2.9 on 2021-12-20 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0003_remove_scrapingstate_spider_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapingstate',
            name='scraping_schedule',
            field=models.CharField(default='0 0 * * * *', max_length=30),
        ),
    ]
