# Generated by Django 3.2.8 on 2022-01-27 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0004_scrapingstate_scraping_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapingstate',
            name='scraping_schedule',
            field=models.CharField(default='0 0 * * *', max_length=30),
        ),
    ]
