# Generated by Django 3.2.12 on 2022-03-24 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0020_alter_productpage_category_preview_url'),
        ('crawler', '0005_alter_scrapingstate_scraping_schedule'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScrapingState',
            new_name='CrawlerState',
        ),
    ]
