# Generated by Django 3.2.12 on 2022-03-31 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0006_rename_scrapingstate_crawlerstate'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='crawlerstate',
            table='crawlerstate',
        ),
    ]