# Generated by Django 3.2.9 on 2021-12-03 12:18
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplace',
            name='image_logo_url',
            field=models.URLField(blank=True),
        ),
    ]
