from django.db import migrations
from django.db import models
2  # Generated by Django 3.2.9 on 2021-12-02 14:44


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
