# Generated by Django 3.2.9 on 2021-12-06 10:18
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_marketplace_image_logo_url'),
        ('marketplace', '0003_productstate_rating'),
    ]

    operations = [
    ]
