# Generated by Django 3.2.9 on 2021-12-06 12:16
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_productstate_review_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstate',
            name='rating',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='productstate',
            name='review_count',
            field=models.IntegerField(),
        ),
    ]
