# Generated by Django 3.2.9 on 2021-12-12 21:15
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0009_alter_productstate_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('SMARTPHONE', 'Smartphone'), ('NOTEBOOK', 'Notebook'), ('MONITOR', 'Monitor'), ('DESKTOP', 'Desktop'), ('TV', 'TV'), ('TABLET', 'Tablet'), (
                'HEADPHONE', 'Headphones'), ('LEGO', 'ConstructionSet'), ('COSMETIC', 'Cosmetic'), ('BOOK', 'Book'), ('SMART_ACCESSORY', 'SmartAccessory')], max_length=62),
        ),
    ]
