# Generated by Django 3.2.8 on 2021-12-26 19:59
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0013_auto_20211222_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpage',
            name='marketplace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace', to='marketplace.marketplace'),
        ),
        migrations.AlterField(
            model_name='productpage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_pages', to='marketplace.product'),
        ),
        migrations.AlterField(
            model_name='productstate',
            name='product_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_states', to='marketplace.productpage'),
        ),
    ]
