# Generated by Django 3.2.8 on 2021-12-23 11:41
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0013_auto_20211222_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstate',
            name='availability',
            field=models.CharField(choices=[('BackOrder', 'BackOrder'), ('Discontinued', 'Discontinued'), ('InStock', 'InStock'), ('InStoreOnly', 'InStoreOnly'), ('LimitedAvailability', 'LimitedAvailability'), (
                'OnlineOnly', 'OnlineOnly'), ('OutOfStock', 'OutOfStock'), ('PreOrder', 'PreOrder'), ('PreSale', 'PreSale'), ('SoldOut', 'SoldOut'), ('NoInfo', None)], default='', max_length=24),
        ),
    ]
