# Generated by Django 3.2.8 on 2021-11-02 14:25
import datetime

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapingState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spider_name', models.CharField(choices=[('schema.org', 'schema.org')], max_length=32)),
                ('last_scraping', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0))),
                ('marketplace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='marketplace.marketplace')),
            ],
        ),
    ]
