{{ readFile "defaults.yaml" }}

commonLabels:
  tier: "infra"

releases:
  - name: prometheus
    namespace: monitoring
    chart: prometheus-community/kube-prometheus-stack
    installed: {{ .Values.monitoring.enabled | toYaml }}
    version: 18.0.1
    values:
      - releases/values-prometheus-stack.yaml

  - name: ingress-nginx
    namespace: kube-system
    chart: ingress-nginx/ingress-nginx
    version: 3.36.0
    values:
      - releases/values-ingress-nginx.yaml
      - controller:
          metrics:
            enabled: {{ .Values.monitoring.enabled | toYaml }}
    needs:
      - prometheus
