{{- range .Values.certificates }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .secretName }}-certificate
  namespace: {{ $.Release.Namespace }}
spec:
  secretName: {{ .secretName }}
  dnsNames:
    - {{ .dnsName }}
  usages:
    - digital signature
    - key encipherment
  issuerRef:
    name: {{ .issuer }}
    kind: Issuer
    group: cert-manager.io
{{ end }}
