repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        exclude: "(^|/)templates/|(^|/)helmfile*"

      - id: name-tests-test
      - id: double-quote-string-fixer

  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.5.3
    hooks:
      - id: autopep8
        args: [-i, --max-line-length=150]

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.29.0
    hooks:
      - id: pyupgrade
        args: [--py36-plus]

  - repo: https://github.com/asottile/reorder_python_imports
    rev: v2.6.0
    hooks:
      - id: reorder-python-imports
        args: [--py3-plus]

  - repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies: [flake8-typing-imports==1.6.0]
        args: [--ignore=W501, --ignore=E501, --max-line-length=150, --min-python-version=3.7]

  - repo: https://github.com/pre-commit/pre-commit
    rev: v2.6.0
    hooks:
      - id: validate_manifest
