environments:
  default:
    values:
      - monitoring:
          enabled: false
      - backend:
          tag: test
  prod:
    values:
      - monitoring:
          enabled: false
      - backend:
          tag: latest

helmfiles:
  - path: "helmfile/00-infra.yaml"
    values:
    - # pass the current state values to the sub-helmfile
{{ toYaml .Environment.Values | indent 6 }}

  - path: "helmfile/01-database.yaml"
    values:
    - # pass the current state values to the sub-helmfile
{{ toYaml .Environment.Values | indent 6 }}

  - path: "helmfile/10-application.yaml"
    values:
    - # pass the current state values to the sub-helmfile
{{ toYaml .Environment.Values | indent 6 }}
