apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "worker.fullname" . }}
spec:
  scaleTargetRef:
    name: {{ include "worker.fullname" . }}
  cooldownPeriod:  60
  minReplicaCount: 1
  maxReplicaCount: 10
  triggers:
    - type: prometheus
      metadata:
        serverAddress: http://prometheus-operated.monitoring.svc:9090/prometheus
        metricName: rq_worker_total_amount
        threshold: '3'
        query: sum(rq_jobs{status="queued", queue="crawler-feed"})
