apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: prometheus-scaledobj
spec:
  scaleTargetRef:
    name: {{ include "worker.fullname" . }}
  triggers:
    - type: prometheus
      metadata:
        serverAddress: http://10.244.0.12:8080/prometheus
        metricName: rq_worker_total_amount
        threshold: '3'
        query: count(rq_jobs{status=~"queued", queue=~"crawler-feed"})
