apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-{{ .Release.Namespace }}
spec:
  acme:
    # You must replace this email address with your own.
    # Let's Encrypt will use this to contact you about expiring
    # certificates, and issues related to your account.
    email: {{ .Values.email }}
    server: {{ .Values.server }}
    preferredChain: "ISRG Root X1"
    privateKeySecretRef:
      # Secret resource that will be used to store the account's private key.
      name: {{ .Release.Namespace }}-issuer-account-key
    # Add a single challenge solver, HTTP01 using nginx
    solvers:
    - http01:
        ingress:
          class: nginx
