{{ readFile "defaults.yaml" }}

commonLabels:
  tier: "infra"

releases:
  - name: prometheus-stack
    namespace: monitoring
    chart: prometheus-community/kube-prometheus-stack
    installed: {{ .Values.monitoring.enabled | toYaml }}
    version: 23.2.0
    values:
      - releases/prometheus-stack/values.yaml
      - releases/prometheus-stack/values-{{ .Environment.Name }}.yaml
      - grafana:
          adminUser: {{ .Values.monitoring.grafana.user | toYaml }}
          adminPassword: {{ .Values.monitoring.grafana.pass | toYaml }}

  - name: alerts-k8s
    namespace: monitoring
    chart: ../charts/alerts-k8s
    installed: {{ .Values.monitoring.enabled | toYaml }}
    needs:
      - prometheus-stack

  - name: ingress-nginx
    namespace: kube-system
    chart: ingress-nginx/ingress-nginx
    version: 3.36.0
    needs:
      - prometheus-stack
    values:
      - releases/ingress-nginx/values.yaml
      - releases/ingress-nginx/values-{{ .Environment.Name }}.yaml
      - controller:
          metrics:
            enabled: {{ .Values.monitoring.enabled | toYaml }}

  # Certificates
  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: v1.6.1
    installed: {{ .Values.certManager.enabled | toYaml }}
    values:
      - releases/cert-manager/values.yaml
      - prometheus:
          enabled: {{ .Values.monitoring.enabled | toYaml }}

  - name: cert-issuer-backoffice
    namespace: monitoring
    chart: ../charts/cert-issuer
    installed: {{ .Values.certManager.enabled | toYaml }}
    values:
      - releases/cert-issuer/values-backoffice-{{ .Environment.Name }}.yaml
    needs:
      - cert-manager

  - name: certificates-backoffice
    namespace: monitoring
    chart: ../charts/certificates
    installed: {{ .Values.certManager.enabled | toYaml }}
    values:
      - releases/certificates/values-backoffice-{{ .Environment.Name }}.yaml
    needs:
      - cert-cluster-issuer
