{{ readFile "defaults.yaml" }}

commonLabels:
  tier: "infra"

releases:
  - name: prometheus
    namespace: monitoring
    chart: prometheus-community/kube-prometheus-stack
    installed: {{ .Values.monitoring.enabled | toYaml }}
    version: 18.0.1
    values:
      - releases/values-prometheus-stack.yaml

  - name: ingress-nginx
    namespace: kube-system
    chart: ingress-nginx/ingress-nginx
    version: 3.36.0
    values:
      - releases/values-ingress-nginx.yaml
      - controller:
          metrics:
            enabled: {{ .Values.monitoring.enabled | toYaml }}

  # REDIS
  - name: redis
    namespace: default
    chart: bitnami/redis
    version: 15.5.1
    values:
      - releases/values-redis.yaml

  - name: redis-exporter
    namespace: monitoring
    chart: prometheus-community/prometheus-redis-exporter
    installed: {{ .Values.monitoring.enabled | toYaml }}
    version: 4.6.0
    values:
      - releases/values-redis-exporter.yaml

  # POSTGRES
  - name: postgres
    namespace: default
    chart: bitnami/postgresql
    version: 10.3.0
    values:
      - releases/values-postgres.yaml

  - name: postgres-exporter
    namespace: monitoring
    chart: prometheus-community/prometheus-postgres-exporter
    installed: {{ .Values.monitoring.enabled | toYaml }}
    version: 2.3.7
    values:
      - releases/values-postgres-exporter.yaml
