{{ readFile "defaults.yaml" }}

commonLabels:
  tier: "infra"

releases:
  - name: prometheus-stack
    namespace: monitoring
    chart: prometheus-community/kube-prometheus-stack
    installed: {{ .Values.monitoring.enabled | toYaml }}
    version: 18.0.1
    values:
      - releases/prometheus-stack/values.yaml
      - releases/prometheus-stack/values-{{ .Environment.Name }}.yaml
      - grafana:
          adminUser: {{ .Values.monitoring.grafana.user | toYaml }}
          adminPassword: {{ .Values.monitoring.grafana.pass | toYaml }}

  - name: ingress-nginx
    namespace: kube-system
    chart: ingress-nginx/ingress-nginx
    version: 3.36.0
    needs:
      - prometheus-stack
    values:
      - releases/ingress-nginx/values.yaml
      - releases/ingress-nginx/values-{{ .Environment.Name }}.yaml
      - controller:
          metrics:
            enabled: {{ .Values.monitoring.enabled | toYaml }}

  - name: cert-manager-crd
    namespace: cert-manager
    chart: ../charts/cert-manager-crd

  - name: cert-manager
    namespace: cert-manager
    chart: jetstack\cert-manager
    version: v1.6.1
    installed: {{ .Values.certManager.enabled | toYaml }}
    needs:
      - cert-manager-crd

  # REDIS
  - name: redis
    namespace: {{ .Values.namespace }}
    chart: bitnami/redis
    version: 15.5.1
    installed: {{ .Values.redis.enabled | toYaml }}
    values:
      - releases/redis/values.yaml
      - releases/redis/values-{{ .Environment.Name }}.yaml

  - name: redis-exporter
    namespace: {{ .Values.namespace }}
    chart: prometheus-community/prometheus-redis-exporter
    installed: {{ .Values.monitoring.enabled | toYaml }}
    version: 4.6.0
    needs:
      - prometheus-stack
    values:
      - releases/redis-exporter/values.yaml

  # POSTGRES
  - name: postgres
    namespace: {{ .Values.namespace }}
    chart: bitnami/postgresql
    version: 10.3.0
    installed: {{ .Values.postgres.enabled | toYaml }}
    values:
      - releases/postgres/values.yaml
      - releases/postgres/values-{{ .Environment.Name }}.yaml
      - postgresqlDatabase: {{ .Values.postgres.dbName | toYaml }}
      - postgresqlUsername: {{ .Values.postgres.user | toYaml }}
      - postgresqlPassword: {{ .Values.postgres.pass | toYaml }}

  - name: postgres-exporter
    namespace: {{ .Values.namespace }}
    chart: prometheus-community/prometheus-postgres-exporter
    installed: {{ .Values.monitoring.enabled | toYaml }}
    version: 2.3.7
    needs:
      - prometheus-stack
    values:
      - releases/postgres-exporter/values.yaml
      - config:
          datasource:
            host: {{ .Values.postgres.host | toYaml }}
            user: {{ .Values.postgres.user | toYaml }}
            password: {{ .Values.postgres.pass | toYaml }}
            database: {{ .Values.postgres.dbName | toYaml }}
            port: {{ .Values.postgres.port | toYaml }}
