{{ readFile "defaults.yaml" }}

commonLabels:
  tier: "backend"

releases:
  - name: cms
    namespace: default
    chart: ../charts/cms
    values:
      - releases/backend/values-cms.yaml
      - image:
          tag: {{ .Values.backend.tag }}

  - name: worker-crawler
    namespace: default
    chart: ../charts/worker
    values:
      - releases/backend/values-worker.yaml
      - releases/backend/values-worker-crawler.yaml
      - image:
          tag: {{ .Values.backend.tag }}

  - name: worker-etc
    namespace: default
    chart: ../charts/worker
    values:
      - releases/backend/values-worker.yaml
      - releases/backend/values-worker-etc.yaml
      - image:
          tag: {{ .Values.backend.tag }}
