{{ readFile "defaults.yaml" }}

commonLabels:
  tier: "app"

releases:
  - name: cms
    namespace: default
    chart: ../charts/cms
    labels:
      side: "backend"
    values:
      - releases/backend/cms/values.yaml
      - releases/backend/cms/values-{{ .Environment.Name }}.yaml
      - image:
          tag: {{ .Values.app.tag }}

  - name: worker-crawler
    namespace: default
    chart: ../charts/worker
    labels:
      side: "backend"
    values:
      - releases/backend/worker/values.yaml
      - releases/backend/worker/values-{{ .Environment.Name }}.yaml
      - releases/backend/worker/values-crawler.yaml
      - image:
          tag: {{ .Values.app.tag }}

  - name: worker-etc
    namespace: default
    chart: ../charts/worker
    labels:
      side: "backend"
    values:
      - releases/backend/worker/values.yaml
      - releases/backend/worker/values-{{ .Environment.Name }}.yaml
      - releases/backend/worker/values-etc.yaml
      - image:
          tag: {{ .Values.app.tag }}

  - name: site
    namespace: default
    chart: ../charts/site
    labels:
      side: "frontend"
    values:
      - releases/frontend/values.yaml
      - releases/frontend/values-{{ .Environment.Name }}.yaml
      - image:
          tag: {{ .Values.app.tag }}
