configuration: Dev
secretKey: ''

redis:
  rq:
    host: "localhost"
    port: "6379"
    db: "0"
  storage:
    host: "localhost"
    port: "6379"
    db: "0"

postgres:
  dbname: "byprice24"
  username: ""
  password: ""
  host: "localhost"
  port: "5432"

domain:
  api: ''
  admin: ''

elasticsearch:
  url: 'localhost:9200'
