metrics-server:
  enabled: true
prometheus:
  monitor:
    enabled: false
    additionalLabels: {}
    namespace: ""
    interval: ""
    scrapeTimeout: ""
    proxyUrl: ""
    honorLabels: false

prometheusOperator:
  resources:
    limits:
      cpu: 100m
      memory: 200Mi
    requests:
      cpu: 10m
      memory: 100Mi

# Prometheus settings
prometheus:
  prometheusSpec:
    # allow discovery of third party service monitor
    serviceMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 400Mi

  ingress:
    enabled: true
    ingressClassName: nginx

# Alertmanager settings
alertmanager:
  enabled: true
  ingress:
    enabled: true
    ingressClassName: nginx


# Grafana settings
grafana:
  enabled: true

  ingress:
    enabled: true
    ingressClassName: nginx
