# Prometheus settings
prometheus:
  prometheusSpec:
    routePrefix: "/prometheus"

  ingress:
    annotations:
      nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    tls:
      - secretName: findprice-site-tls
        hosts:
          - findprice.site
          - www.findprice.site
    hosts:
      - www.findprice.site
    pathType: Prefix
    paths:
      - "/prometheus(/|$)(.*)"

# Alertmanager settings
alertmanager:
  ingress:
    enabled: false # TODO Make auth proxy to access this site
    annotations:
      nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
      nginx.ingress.kubernetes.io/rewrite-target: /$2
    tls:
      - secretName: findprice-site-tls
        hosts:
          - findprice.site
          - www.findprice.site
    hosts:
      - www.findprice.site
    pathType: Prefix
    paths:
      - "/alertmanager(/|$)(.*)"

# Grafana settings
grafana:
  grafana.ini:
    server:
      domain: www.findprice.site
      root_url: https://findprice.site:1080/grafana/
      serve_from_sub_path: true

  ingress:
    annotations:
      nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
      nginx.ingress.kubernetes.io/rewrite-target: /$2
    tls:
      - secretName: findprice-site-tls
        hosts:
          - findprice.site
          - www.findprice.site
    hosts:
      - www.findprice.site
    pathType: Prefix
    path: "/grafana(/|$)(.*)"
