# Generated by Django 4.0 on 2021-12-17 08:45
import datetime

from django.db import migrations
from django.db import models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queryhistory',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 17, 8, 45, 31, 594488, tzinfo=utc)),
        ),
    ]
