configmap: |-
  appendonly no
  save ""

architecture: standalone
auth:
  enabled: false

cluster:
  enabled: false

serviceAccount:
  create: true
  name: redis

master:
  persistence:
    enabled: false
