configmap: |-
  appendonly no
  save ""

architecture: standalone
auth:
  enabled: false

cluster:
  enabled: false

serviceAccount:
  create: true
  name: redis

master:
  persistence:
    enabled: false

  resources:
    requests:
      cpu: "100m"
      memory: "100Mi"
    limits:
      memory: "100Mi"


replica:
  persistence:
    enabled: false

  resources:
    requests:
      cpu: "100m"
      memory: "150Mi"
    limits:
      memory: "150Mi"
