environments:
  local:
    values:
      - ./helmfile/values-local.yaml

  prod:
    values:
      - ./helmfile/values-prod.yaml.gotmpl

helmfiles:
  - path: "helmfile/00-infra.yaml"
    values:
    - # pass the current state values to the sub-helmfile
{{ toYaml .Environment.Values | indent 6 }}

  - path: "helmfile/10-infra-app.yaml"
    values:
    - # pass the current state values to the sub-helmfile
{{ toYaml .Environment.Values | indent 6 }}

  - path: "helmfile/11-app.yaml"
    values:
    - # pass the current state values to the sub-helmfile
{{ toYaml .Environment.Values | indent 6 }}
