kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: byprice24
networking:
  apiServerAddress: "127.0.0.1"
  apiServerPort: 6443
nodes:
  - role: control-plane
    image: kindest/node:v1.21.2
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
            authorization-mode: "AlwaysAllow"
    extraPortMappings:
      - containerPort: 80
        hostPort: 1080
        protocol: TCP
      - containerPort: 30101 # postgres
        hostPort: 5432
        protocol: TCP
      - containerPort: 30102 # redis
        hostPort: 6379
        protocol: TCP
