# Generated by Django 3.2.9 on 2021-12-06 10:33
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_merge_20211206_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstate',
            name='review_count',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
