# Generated by Django 3.2.9 on 2021-12-07 20:17
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_auto_20211206_1216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='preview_url',
            new_name='preview_url',
        ),
    ]
