# Generated by Django 3.2.9 on 2021-12-07 21:00
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_rename_image_url_product_preview_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstate',
            name='availability',
            field=models.CharField(default='', max_length=16),
        ),
    ]
