# Generated by Django 3.2.8 on 2021-12-18 21:25
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0011_auto_20211216_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplace',
            name='description',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('MOBILE', 'Mobile'), ('NOTEBOOK', 'Notebook'), ('DISPLAY', 'Monitor'), ('DESKTOP', 'Desktop'), ('TV', 'TV'), ('TABLET', 'Tablet'), (
                'HEADPHONE', 'Headphones'), ('LEGO', 'ConstructionSet'), ('COSMETIC', 'Cosmetic'), ('BOOK', 'Book'), ('SMART_GADGET', 'SmartGadget')], max_length=64),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='productpage',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
