# Generated by Django 3.2.8 on 2021-12-22 17:56
import datetime

from django.db import migrations
from django.db import models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0012_auto_20211218_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstate',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='productstate',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='productstate',
            name='review_count',
            field=models.IntegerField(default=0),
        ),
    ]
