# Generated by Django 3.2.8 on 2022-01-18 16:22
import datetime

from django.db import migrations
from django.db import models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0014_auto_20211226_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstate',
            name='last_check',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=utc)),
        ),
    ]
