# Generated by Django 3.2.8 on 2022-02-15 07:59
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0016_auto_20220214_2001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
