# Generated by Django 3.2.8 on 2022-02-15 18:32
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0017_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpage',
            name='name',
            field=models.CharField(max_length=192),
        ),
    ]
