# Generated by Django 3.2.8 on 2022-03-08 15:35
import django.db.models.deletion
from django.db import migrations
from django.db import models


def forwards_func(apps, schema_editor):

    ProductPage = apps.get_model('marketplace', 'ProductPage')
    product_pages = ProductPage.objects.all()

    for product_page in product_pages:
        product_page.preview_url = product_page.product.preview_url
        product_page.category = product_page.product.category
        product_page.save()


def reverse_func(apps, schema_editor):
    ProductPage = apps.get_model('marketplace', 'ProductPage')
    product_pages = ProductPage.objects.all()

    for product_page in product_pages:
        product_page.preview_url = None
        product_pages.category = None
        product_page.save()


class Migration(migrations.Migration):
    dependencies = [
        ('marketplace', '0018_alter_productpage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpage',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='marketplace.category'),
        ),
        migrations.AddField(
            model_name='productpage',
            name='preview_url',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.RunPython(forwards_func, reverse_func)
    ]
