# Generated by Django 3.2.8 on 2022-03-10 09:43
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0019_auto_20220308_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpage',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.category'),
        ),
        migrations.AlterField(
            model_name='productpage',
            name='preview_url',
            field=models.CharField(max_length=256, blank=True),
        ),
    ]
