# Generated by Django 3.2.8 on 2022-03-08 17:05
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0019_auto_20220308_1535'),
    ]

    operations = [
        migrations.RunSQL("""
        UPDATE marketplace_productpage
        SET    preview_url = marketplace_product.preview_url
        FROM   marketplace_product
        WHERE  marketplace_productpage.product_id = marketplace_product.id;
        """
                          ),
        migrations.RunSQL("""
        UPDATE marketplace_productpage
        SET    category_id = marketplace_product.category_id
        FROM   marketplace_product
        WHERE  marketplace_productpage.product_id = marketplace_product.id;
        """
                          ),
    ]
