# Generated by Django 3.2.12 on 2022-04-10 16:21
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0020_alter_productpage_category_preview_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplace',
            name='price_currency',
            field=models.CharField(default='BYN', max_length=8),
        ),
    ]
