# Generated by Django 3.2.12 on 2022-04-12 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0021_marketplace_delivery'),
        ('marketplace', '0021_marketplace_price_currency'),
    ]

    operations = [
    ]
