# Generated by Django 3.2.12 on 2022-04-20 21:18
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0023_auto_20220414_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorygroup',
            name='ru',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
