ingress:
  annotations:
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
  tls:
    - secretName: findprice-by-tls
      hosts:
        - findprice.by
        - www.findprice.by
  hosts:
    - host: www.findprice.by
      paths:
        - path: /
          pathType: Prefix
