resources:
  requests:
    cpu: "15m"
    memory: "45Mi"
  limits:
    cpu: "75m"
    memory: "45Mi"

rq:
  - name: rq
    host: redis-master

rules:
  enabled: true
  failedJobs:
    enabled: true
    threshold: 0
    queues:
      - crawler-result
      - search-query
