coordinating:
  service:
    type: NodePort
    nodePort: 30103
  livenessProbe:
    enabled: false

master:
  replicas: 1
  persistence:
    enabled: false
  livenessProbe:
    enabled: false

data:
  persistence:
    enabled: false
  livenessProbe:
    enabled: false

# Is not working on mac m1
extraConfig:
  bootstrap:
    system_call_filter: false
