architecture: standalone

serviceAccountName: elasticsearch
serviceAccountCreate: true

ES_JAVA_OPTS: "-Xms512m -Xmx768m"

replicas: 1

resources:
  limits:
    memory: 768Mi
  requests:
    cpu: 150m
    memory: 512Mi
