ingress:
  annotations:
    cert-manager.io/issuer: letsencrypt-prod
  tls:
    - secretName: api-findprice-by-tls
      hosts:
        - findprice.by
    - secretName: admin-findprice-site-tls
      hosts:
        - findprice.site
  hosts:
    - host: findprice.by
      paths:
        - path: /api
          pathType: Prefix
    - host: findprice.site
      paths:
        - path: /admin
          pathType: Prefix
        - path: /admin-static
          pathType: Prefix

domain:
  api: findprice.by
  admin: findprice.site

configuration: Prod
