ingress:
  enabled: true
  hosts:
    - host: price24.by
      paths:
        - path: /admin
          pathType: Prefix
        - path: /admin-static
          pathType: Prefix
        - path: /api
          pathType: Prefix
