name: ci-frontend
on:
  workflow_call:
    inputs:
      test:
        required: false
        type: boolean
        default: true
      publish:
        required: false
        type: boolean
        default: false
    secrets:
      DOCKER_USER:
        required: false
      DOCKER_PASS:
        required: false
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '17.x'

      - name: Setup
        working-directory: ./frontend
        run: make setup

      - name: Lint
        working-directory: ./frontend
        run: make lint

      - name: Test
        if: ${{ inputs.test }}
        working-directory: ./frontend
        run: make test

      - name: Build Docker Image
        run: make frontend-image-build IMAGE_TAG=${GITHUB_REF##*/}

      - name: Publish Docker Image
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
        if: ${{ inputs.publish }}
        run: |
          make docker-login DOCKER_USER=$DOCKER_USER DOCKER_PASS=$DOCKER_PASS
          make frontend-image-publish IMAGE_TAG=${GITHUB_REF##*/}
