name: ci-deployment
on:
  workflow_call:
    inputs:
      validate:
        required: false
        type: boolean
        default: true
      deploy:
        required: false
        type: boolean
        default: false
    secrets:
      POSTGRES_DATABASE:
        required: true
      POSTGRES_HOST:
        required: true
      POSTGRES_USER:
        required: true
      POSTGRES_PASS:
        required: true
      POSTGRES_PORT:
        required: true
      GRAFANA_USER:
        required: true
      GRAFANA_PASS:
        required: true
      DJANGO_SECRET:
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup helmfile
        uses: mamezou-tech/setup-helmfile@v0.8.0
        with:
          install-kubectl: ${{ inputs.deploy }}
          helm-version: "v3.6.3"
          helmfile-version: "v0.140.1"

      - name: Validate Local
        if: ${{ inputs.validate }}
        working-directory: ./deployment
        run: |
          make validate-local

      - name: Validate Prod
        if: ${{ inputs.validate }}
        working-directory: ./deployment
        env:
          BACKEND_IMAGE_SHA256: test
          FRONTEND_IMAGE_SHA256: test
          POSTGRES_DATABASE: ${{ secrets.POSTGRES_DATABASE }}
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASS: ${{ secrets.POSTGRES_PASS }}
          POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
          GRAFANA_USER: ${{ secrets.GRAFANA_USER }}
          GRAFANA_PASS: ${{ secrets.GRAFANA_PASS }}
          DJANGO_SECRET: ${{ secrets.DJANGO_SECRET }}
        run: |
          mkdir /home/runner/.kube
          echo "${{ secrets.KUBECONFIG }}" > /home/runner/.kube/config
          touch .env
          make validate-prod

      - name: Deploy
        if: ${{ inputs.deploy }}
        working-directory: ./deployment
        env:
          POSTGRES_DATABASE: ${{ secrets.POSTGRES_DATABASE }}
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASS: ${{ secrets.POSTGRES_PASS }}
          POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
          GRAFANA_USER: ${{ secrets.GRAFANA_USER }}
          GRAFANA_PASS: ${{ secrets.GRAFANA_PASS }}
          DJANGO_SECRET: ${{ secrets.DJANGO_SECRET }}
        run: |
          mkdir /home/runner/.kube
          echo "${{ secrets.KUBECONFIG }}" > /home/runner/.kube/config
          touch .env
          make helmfile-prod BACKEND_IMAGE_TAG=${GITHUB_REF##*/} FRONTEND_IMAGE_TAG=${GITHUB_REF##*/} GIT_RELEASE=${GITHUB_REF##*/} ARGS=apply
