name: Backend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/*'
      - backend/**
      - src/**
      - fixtures/**
      - testdata/**
      - Pipfile
      - Dockerfile
      - Makefile

concurrency:
  group: ci-backend-${{ github.ref }}
  cancel-in-progress: true

jobs:
  call-ci-backend:
    uses: zifter/byprice24/.github/workflows/_ci_backend.yaml@main
