name: deployment-ci
on:
  push:
    branches:
      - main
    paths:
      - '**/deployment-ci.yaml'
      - deployment/**
      - Makefile

  pull_request:
    branches:
      - main
    paths:
      - '**/deployment-ci.yaml'
      - deployment/**
      - Makefile

jobs:
  helmfile-validate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup helmfile
        uses: mamezou-tech/setup-helmfile@v0.8.0
        with:
          install-kubectl: no
          helm: "v3.6.3"
          helmfile-version: "v0.140.1"

      - name: Validate
        working-directory: ./deployment
        env:
          BACKEND_IMAGE_SHA256: test
          FRONTEND_IMAGE_SHA256: test
          POSTGRES_DATABASE: ${{ secrets.POSTGRES_DATABASE }}
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASS: ${{ secrets.POSTGRES_PASS }}
          POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
          GRAFANA_USER: ${{ secrets.GRAFANA_USER }}
          GRAFANA_PASS: ${{ secrets.GRAFANA_PASS }}
        run: |
          make validate
