name: deploy
on:
  workflow_run:
    workflows: ["backend-ci", "deployment-ci", "frontend-ci"]
    branches: [main]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup helmfile
        uses: mamezou-tech/setup-helmfile@v0.8.0
        with:
          install-kubectl: yes
          helm: "v3.6.3"
          helmfile-version: "v0.140.1"

      - name: Deploy
        working-directory: ./deployment
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
          POSTGRES_DATABASE: ${{ secrets.POSTGRES_DATABASE }}
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASS: ${{ secrets.POSTGRES_PASS }}
          POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
          GRAFANA_USER: ${{ secrets.GRAFANA_USER }}
          GRAFANA_PASS: ${{ secrets.GRAFANA_PASS }}
        run: |
          make prod-deploy
