name: deploy
on:
  workflow_run:
    workflows: ["backend-ci", "deployment-ci", "frontend-ci"]
    branches: [main]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: steebchen/kubectl@v2.0.0
        env:
          POSTGRES_DATABASE: ${{ secrets.POSTGRES_DATABASE }}
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASS: ${{ secrets.POSTGRES_PASS }}
          POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
          GRAFANA_USER: ${{ secrets.GRAFANA_USER }}
          GRAFANA_PASS: ${{ secrets.GRAFANA_PASS }}
        with:
          config: ${{ secrets.KUBECONFIG }}
          command: cd deployment && make prod-deploy
