name: frontend-ci
on:
  push:
    branches:
      - main
    paths:
      - '**/frontend-ci.yaml'
      - frontend/**
      - Makefile

  pull_request:
    branches:
      - main
    paths:
      - '**/frontend-ci.yaml'
      - frontend/**
      - Makefile

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '17.x'

      - name: Setup
        working-directory: ./frontend
        run: make setup

      - name: Lint
        working-directory: ./frontend
        run: make lint

      - name: Test
        working-directory: ./frontend
        run: make test

      - name: Build Docker Image
        run: make frontend-image-build IMAGE_TAG=zifter/byprice24-site:${GITHUB_REF##*/}

      - name: Publish Docker Image
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        run: |
          make docker-login DOCKER_USER=$DOCKER_USER DOCKER_PASS=$DOCKER_PASS
          make frontend-image-publish IMAGE_TAG=zifter/byprice24-site:${GITHUB_REF##*/}
