name: Frontend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/*'
      - frontend/**
      - Makefile

concurrency:
  group: ci-frontend-${{ github.ref }}
  cancel-in-progress: true

jobs:
  call-ci-frontend:
    uses: zifter/byprice24/.github/workflows/_ci_frontend.yaml@main
