name: Release
concurrency: production
on:
  workflow_dispatch: {}
  release:
    types: [published]

jobs:
  call-ci-backend:
    uses: zifter/byprice24/.github/workflows/_ci_backend.yaml@main
    with:
      publish: true
      test: false

  call-ci-frontend:
    uses: zifter/byprice24/.github/workflows/_ci_frontend.yaml@main
    with:
      publish: true
      test: false

  call-deploy:
    needs:
      - call-ci-frontend
      - call-ci-backend
    uses: zifter/byprice24/.github/workflows/_ci_deployment.yaml@main
    with:
      deploy: true
      validate: true
    secrets:
      POSTGRES_DATABASE: ${{ secrets.POSTGRES_DATABASE }}
      POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASS: ${{ secrets.POSTGRES_PASS }}
      POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
      GRAFANA_USER: ${{ secrets.GRAFANA_USER }}
      GRAFANA_PASS: ${{ secrets.GRAFANA_PASS }}
      DJANGO_SECRET: ${{ secrets.DJANGO_SECRET }}
